name = "bmgone-payroll"
compatibility_date = "2024-09-23"

# Pages build output directory
pages_build_output_dir = "."

[env.production]
vars = { ENVIRONMENT = "production", API_BASE = "https://pay.bmgone.com/api" }

[env.preview]
vars = { ENVIRONMENT = "preview", API_BASE = "https://pay.bmgone.com/api" }

# Environment variables
[vars]
API_BASE = "https://pay.bmgone.com/api"
ENVIRONMENT = "production"
